from algosdk import account, mnemonic

private_key_a, public_key_a = account.generate_account()
private_key_b, public_key_b = account.generate_account()
private_key_c, public_key_c = account.generate_account()
private_key_d, public_key_d = account.generate_account()
private_key_e, public_key_e = account.generate_account()
mnemonic_a = mnemonic.from_private_key(private_key_a)
mnemonic_b = mnemonic.from_private_key(private_key_b)
mnemonic_c = mnemonic.from_private_key(private_key_c)
mnemonic_d = mnemonic.from_private_key(private_key_d)
mnemonic_e = mnemonic.from_private_key(private_key_e)

with open('../.env', 'w') as f:
    f.write(f'CREATOR_ADDRESS="{public_key_a}"\n')
    f.write(f'CREATOR_SECRET="{private_key_a}"\n')
    f.write(f'CREATOR_MNEMONIC="{mnemonic_a}"\n')
    f.write(f'COLLAB_1_ADDRESS="{public_key_b}"\n')
    f.write(f'COLLAB_1_SECRET="{private_key_b}"\n')
    f.write(f'COLLAB_1_MNEMONIC="{mnemonic_b}"\n')
    f.write(f'COLLAB_2_ADDRESS="{public_key_c}"\n')
    f.write(f'COLLAB_2_SECRET="{private_key_c}"\n')
    f.write(f'COLLAB_2_MNEMONIC="{mnemonic_c}"\n')
    f.write(f'COLLAB_3_ADDRESS="{public_key_d}"\n')
    f.write(f'COLLAB_3_SECRET="{private_key_d}"\n')
    f.write(f'COLLAB_3_MNEMONIC="{mnemonic_d}"\n')
    f.write(f'BUYER_1_ADDRESS="{public_key_e}"\n')
    f.write(f'BUYER_1_SECRET="{private_key_e}"\n')
    f.write(f'BUYER_1_MNEMONIC="{mnemonic_e}"\n')
    f.flush()
